name: Generated Signed APK Debug and Release

on:
  pull_request:
    branches:
      - 'M[0-9]'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-apk:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Create APK Release
      - name: Create the Keystore
        env:
          encoded_string: ${{ secrets.SIGNING_KEY }}
        run: |
          temp_keystore_path="${RUNNER_TEMP}"/keystore
          mkdir -p $temp_keystore_path
          echo $encoded_string | base64 -di > "${temp_keystore_path}"/keystore.jks
          
      - name: Create keystore properties
        env:
          key_store_password: ${{ secrets.KEY_STORE_PASSWORD }}
          key_password: ${{ secrets.KEY_PASSWORD }}
          alias: ${{ secrets.ALIAS }}
        run: |
          bash update_properties.sh "keystore/keystore.jks" $key_store_password $alias $key_password

      # Create APK Debug
      - name: Build Debug apk
        run: ./gradlew assembleDebug --stacktrace

      - name: Build Release apk
        run: ./gradlew assembleRelease

      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/
